### ISSUE TITLE
[REQ] ban after x detections

### ISSUE THREAD

**Issue by lunatixxx** [dysphie/sm-tickbase-manipulation-fix#3]
Could you add a function that will ban after for example 3 detection on the player in less than let's say 10 minutes (both could be adjusted)

**Comment by dysphie** [comment]
I don't really plan to as there isn't a detection/time combination that is fail proof (3 in 10 minutes is very common for legit players, for example). This isn't anti-cheat software. The logs are more so just a tip that someone might be cheating. It's up to server admins to use the information responsibly together with other variables, etc.
